### ISSUE TITLE
School Districts

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/myBloomington#9]
We would like to display appropriate `School Districts` via an address search.

**Comment by laurahaley** [comment]
We don't have current school district boundaries.  It used to be a bit
dicey because people feel strongly about that kind of thing and make big
decisions based on it.  If we give the wrong info, it could be a big
problem. I'd feel better if we try to work with the school systems to get
their input and buy in about putting that info into mybloomington and
working out how we could keep it maintained.  Are we only concerned about
MCCSC which covers all of Bloomington or do we want to also involve RBBS.
My contacts at MCCSC have retired.  We should brainstorm on who can help
get us connected.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by laurahaley** [comment]
Here is the MCCSC page for finding schools.  https://www.mccsc.edu/page/138
They direct people to Monroe County's  Elevate app.
Looks like they have their own address search based on a Tyler Tech
product. Perhaps they have an API.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by adabutch** [comment]
@laurahaley - 

I agree & good thinking, thanks for following along here! I have a connect in the MCCSC administration building I would be happy to call up for additional infos. If we decide this is too much to get into and be responsible for, we could display nearby schools related to an address relatively easy via our geoServer's publicgis:Schools.

**also note:** http://versalookup.mccsc.edu/elinkrp/Students/BasicTransBoundarySearch.aspx

**Comment by adabutch** [comment]
Chatting w. Tim Pritchett (MSSCS - IT Director) about potential avenues to get this.

**Comment by adabutch** [comment]
Tammy Behrman - Monroe Co. GIS

**Comment by adabutch** [comment]
This data is not available, without some heavy lifting.

Since we're already displaying nearby `Schools`, relative to an Address ...

Might be worth just linking here:
http://versalookup.mccsc.edu/elinkrp/Students/BasicTransBoundarySearch.aspx

**Comment by adabutch** [comment]
Pre-populating the **`District`** lookup query via an additional grade selection on my end. Radical!

Downside to this, if it changes without notifying us, it'll be busted till then.
